# Generated by Django 3.0.3 on 2020-02-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200227_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner_name',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
